config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users

  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :students, only: [:index, :show, :edit, :update, :new, :create]
  get '/results', to: 'students#results', as: :public_results
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :email, :clave_unica, :points, presence: true
  validates :email, :clave_unica, uniqueness: true
  def self.search(query)
    where("clave_unica = ?", "#{query}")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def is_admin?
    if !current_user.is_admin
      flash[:alert] = "Acceso no permitido"
      redirect_to root_path
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    render :layout => "home"
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  respond_to :html
  before_action :authenticate_user!, only: [:index, :create, :edit, :new]
  before_action :set_student, only: [:update, :show, :edit]
  before_action :is_admin?, only: [:index, :create, :edit, :new]

  def index
    @students = Student.all.order("clave_unica ASC")
    respond_with(@students)
  end

  def results
    if params[:search]
      @students = Student.search(params[:search]).order("clave_unica ASC")
    else
      @students = Student.all.order("clave_unica ASC")
    end
    respond_with(@students)
  end

  def show
    respond_with(@student)
  end

  def edit
    respond_with(@student)
  end

  def update
    @student.update(student_params)
    respond_with(@student)
  end

  def new
    @student = Student.new
    respond_with(@student)
  end

  def create
    @student = Student.new(student_params)
    @student.save
    respond_with(@student)
  end

  def find
    @student = Student.where(clave_unica: params[:clave_unica])
    respond_with(@student)
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:clave_unica, :email, :points)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Ecopoints</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default" style="margin-bottom: 0px;">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <%= link_to "Ecopoints", root_path, class: "navbar-brand" %>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Estudiantes", students_path %></li>
          <li><%= link_to "Agregar Nuevo", new_student_path %></li>
          <li><%= link_to "Log Out", logout_path %></li>
        <% end %>
      </ul>
    </div><!-- /.container-fluid -->
  </nav>

  <%= yield %>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Ecopoints</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav id="main-nav" class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Estudiantes", students_path %></li>
          <li><%= link_to "Agregar Nuevo", new_student_path %></li>
          <li><%= link_to "Log Out", logout_path %></li>
        <% end %>
      </ul>
    </div><!-- /.container-fluid -->
  </nav>

<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<section id="main-hero" class="jumbotron">
  <div class="container">
    <%= image_tag("s6-03.png", class: "img-responsive logo center-block") %>
    <h1 class="text-center">Ecopoints</h1>
  </div>
</section>

<div class="container" style="padding-top: 20px; padding-bottom: 20px;">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-5">
      <%= form_tag(public_results_path, :method => "get", :class => "form-inline") do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: "Clave única", class: "form-control" %>
        </div>
        <button type="submit" class="btn btn-default">Buscar</button>
      <% end %>
      <br />
    </div>
    <div class="col-sm-12">
      <h2 class="text-center">Puntos y Premios</h2>
      <br />
      <%= image_tag("tabla.png", class: "img-responsive center-block") %>
    </div>
  </div>
</div>

app/views/students/_form.html.erb
<%= simple_form_for(@student) do |f| %>
  <div class="form-inputs">
    <%= f.input :clave_unica, required: true %>
    <%= f.input :email %>
    <%= f.input :points, required: true%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<div class="container">
  <br />
  <div class="col-sm-10 col-sm-offset-1">
    <%= render 'form' %>
  </div>
</div>

app/views/students/find.html.erb
<div class="container">
  <br />
  <div class="row">
    <% if current_user %>
    <div class="col-sm-12">
      <%= link_to "Edit", edit_student_path(@student.id) %>
    </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <h1>Clave Única: <%= @student.clave_unica %></h1>
      <h1>Email: <%= @student.email %></h1>
      <h1>Puntos: <%= @student.points %></h1>
    </div>
  </div>
</div>

app/views/students/index.html.erb
<div class="container">
  <div class="row">
    <br />
    <div class="col-sm-12">
      <%= form_tag(public_results_path, :method => "get", :class => "form-inline") do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: "Clave única", class: "form-control" %>
        </div>
        <button type="submit" class="btn btn-default">Buscar</button>
      <% end %>
    </div>
  </div>
  <br />
  <div class="col-sm-12">
    <table class="table">
      <thead>
        <th>Clave Única</th>
        <th>Email</th>
        <th>Puntos</th>
      </thead>

      <tbody>
        <% if @students.count > 0 %>
          <% @students.each do |student| %>
            <tr>
              <td><%= link_to student.clave_unica, student_path(student.id) %></td>
              <td><%= student.email %></td>
              <td><%= student.points %></td>
            </tr>
          <% end %>
        <% else %>
          <div class="alert alert-danger">
            <p>No se encontraron resultados</p>
          </div>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/students/new.html.erb
<div class="container">
  <br />
  <div class="col-sm-10 col-sm-offset-1">
    <%= render 'form' %>
  </div>
</div>

app/views/students/results.html.erb
<div class="container">
  <div class="row">
    <br />
    <div class="col-sm-12">
      <%= form_tag(public_results_path, :method => "get", :class => "form-inline") do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: "Clave única", class: "form-control" %>
        </div>
        <button type="submit" class="btn btn-default">Buscar</button>
      <% end %>
    </div>
  </div>
  <br />
  <div class="col-sm-12">
    <table class="table">
      <thead>
        <th>Clave Única</th>
        <th>Email</th>
        <th>Puntos</th>
      </thead>

      <tbody>
        <% if @students.count > 0 %>
          <% @students.each do |student| %>
            <tr>
              <td><%= link_to student.clave_unica, student_path(student.id) %></td>
              <td><%= student.email %></td>
              <td><%= student.points %></td>
            </tr>
          <% end %>
        <% else %>
          <div class="alert alert-danger">
            <p>No se encontraron resultados</p>
          </div>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/students/show.html.erb
<div class="container">
  <br />
  <div class="row">
    <% if current_user %>
    <div class="col-sm-12">
      <%= link_to "Edit", edit_student_path(@student.id) %>
    </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <h1>Clave Única: <%= @student.clave_unica %></h1>
      <h1>Email: <%= @student.email %></h1>
      <h1>Puntos: <%= @student.points %></h1>
    </div>
  </div>

</div>